branches:
  only:
  - develop
language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
before_install:
- npm install -g grunt-cli
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
env:
  global:
    - NPM_USERNAME=rreverser
    - EMAIL=me@rreverser.com
    - secure: n++5XsU9SToUz4iLG6J//CfCoxAPdD91NyHV77pxsOm9C13mtnVPTByxF6DhRgP6MrBUER3MUfz1q4Zj7PxxJ9qOXgpuUcH1F1wMiJ4IemR7ct0qoaV6eCxBN+gg4nAZDA8798IMjnO8RZ5h2sJfWfm61V82Rg9vth7T0j38Lh8=
    - secure: jRZCZK4i8cAxSV/YcyutjTKeWSZH6I2G25Bw/Ful96VQ175mxSwE8FdgNjKRHWYLB5PR3GtuuvVG7RK2kCEJ1U9LUkpZBDfmvtobx8dz/hYsqgcLWE+Z5nXW/IPjfpfOwEMdGnSenZ5XKnFOrtMPBK2/6VE9zcgarZRZ2NIsHoI=
after_success:
  - |
      if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        git describe --exact-match HEAD &>-
        if [ $? -eq 0 ]; then
          echo "Checking other builds..."
          curl -s -o travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
          python travis_after_all.py
          export $(cat .to_export_back)
          if [ "$BUILD_LEADER" = "YES" ]; then
            if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
              git config --global user.name "Travis-CI"
              git config --global user.email $EMAIL
              echo "Cloning dist..."
              git clone https://$GH_TOKEN@github.com/jDataView/dist2.git ~/dist &>-
              echo "Copying generated files into dist..."
              cp dist/browser/{*.js,*.js.map} ~/dist/
              echo "Committing..."
              pushd ~/dist > /dev/null
              git add .
              git commit -m "Travis build $TRAVIS_BUILD_NUMBER"
              echo "Publishing..."
              git push origin gh-pages &>-
              popd
              echo "Published browser dist."
              grunt npm_publish
            else
              echo "Some of builds were failed."
            fi
          fi
        else
          echo "No tags found, not publishing."
        fi
      else
        echo "Pull request detected, not publishing."
      fi
after_script:
  - echo pull_request=$TRAVIS_PULL_REQUEST leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS
